<?php

namespace TheRealGambo\Ramlfications\Test;

use TheRealGambo\Ramlfications\Parameters\Content;

class ContentParameterTest extends \PHPUnit_Framework_TestCase
{

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testContentParameter()
    {
        $content = new Content('my custom _string_');
        $this->assertEquals('my custom _string_', $content->raw());
        $this->assertEquals('my custom _string_', $content);
        $this->assertEquals('<p>my custom <em>string</em></p>', $content->html());
    }
}