<?php

namespace TheRealGambo\Ramlfications\Test;

use TheRealGambo\Ramlfications\Parameters\Documentation;

class DocumentationParameterTest extends \PHPUnit_Framework_TestCase
{

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testDocumentationParameter()
    {
        $doc = new Documentation(['title' => 'example', 'content' => 'my custom _string_']);
        $this->assertEquals('example', $doc->getTitle()->raw());
        $this->assertEquals('example', $doc->getTitle());
        $this->assertEquals('<p>example</p>', $doc->getTitle()->html());
        $this->assertEquals('my custom _string_', $doc->getContent()->raw());
        $this->assertEquals('my custom _string_', $doc->getContent());
        $this->assertEquals('<p>my custom <em>string</em></p>', $doc->getContent()->html());
    }

    /**
     * @expectedException \TheRealGambo\Ramlfications\Exceptions\InvalidDocumentationNodeException
     */
    public function testDocumentationMissingTitle()
    {
        $doc = new Documentation(['content' => 'my custom _string_']);
    }

    /**
     * @expectedException \TheRealGambo\Ramlfications\Exceptions\InvalidDocumentationNodeException
     */
    public function testDocumentationMissingContent()
    {
        $doc = new Documentation(['title' => 'example']);
    }
}
