<?php

namespace TheRealGambo\Ramlfications\Test;

use Symfony\Component\Yaml\Yaml;
use TheRealGambo\Ramlfications\Nodes\RootNode;
use TheRealGambo\Ramlfications\Parser;

class ProtocolInheritanceTest extends \PHPUnit_Framework_TestCase
{
    private $raml;

    /** @var RootNode $valid */
    private $valid;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

//        $this->raml = Yaml::parse(file_get_contents(__DIR__ . '/raml/1.0/protocol-inheritance.raml'));
//        $parser = new Parser();
//        $this->valid = $parser->parseRaml($this->raml);
//        $this->valid->validate();
    }

//    public function testProtocolInheritanceFromBaseUri()
//    {
//        $route = $this->valid->getResourceByPathAndMethod('/baseuriprotocol', 'get');
//        $this->assertArraySubset(['HTTP'], $route->getProtocols());
//    }
//
//    public function testProtocolInheritanceFromMethod()
//    {
//        $route = $this->valid->getResourceByPathAndMethod('/protocols', 'get');
//        $this->assertArraySubset(['HTTPS'], $route->getProtocols());
//    }
//
//    public function testProtocolInheritanceFromResource()
//    {
//        $route = $this->valid->getResourceByPath('/proto');
//        $this->assertArraySubset(['HTTP', 'HTTPS'], $route->getProtocols());
//    }
//
//    public function testProtocolInheritedFromResourceForMethod()
//    {
//        $route = $this->valid->getResourceByPathAndMethod('/protocols', 'post');
//        $this->assertArraySubset(['HTTP', 'HTTPS'], $route->getProtocols());
//    }
}