<?php

namespace TheRealGambo\Ramlfications\Test;

use TheRealGambo\Ramlfications\Parameters\QueryParameter;

class QueryParameterTest extends \PHPUnit_Framework_TestCase
{

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

//    public function testQueryParameter()
//    {
//        $uri = new QueryParameter([], 'example');
//        $this->assertFalse($uri->getRequired());
//
//        $uri->setRequired(true);
//        $this->assertTrue($uri->getRequired());
//    }
}