<?php

namespace TheRealGambo\Ramlfications\Test;


use TheRealGambo\Ramlfications\Nodes\RootNode;
use TheRealGambo\Ramlfications\Parameters\Content;
use TheRealGambo\Ramlfications\Parameters\Documentation;
use TheRealGambo\Ramlfications\Parser;

class ResponseParameterTest extends \PHPUnit_Framework_TestCase
{

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    private function loadRaml(string $file): RootNode
    {
        $parser = new Parser();
        $data = $parser->parseFile($file, __DIR__ . '/raml/1.0/responses/');
        $raml = $parser->parseRaml($data);
        return $raml;
    }

    public function testResponseHeaders()
    {
        $raml = $this->loadRaml('responsewithheader.raml');

        $route = $raml->getResourceByPath('/example');
        $method = $route->getMethod('get');
        $response = $method->getResponse(200);

        $this->assertCount(2, $response->getHeaders());
    }
}