<?php

namespace TheRealGambo\Ramlfications\Test;

use TheRealGambo\Ramlfications\Nodes\RootNode;
use TheRealGambo\Ramlfications\Parser;

class TypeInheritanceTest extends \PHPUnit_Framework_TestCase
{

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    private function loadRaml(string $file): RootNode
    {
        $parser = new Parser();
        $data = $parser->parseFile($file, __DIR__ . '/raml/1.0/types/');
        $raml = $parser->parseRaml($data);
        return $raml;
    }

    public function testTypeInheritanceValid()
    {
        $raml = $this->loadRaml('arrayType.raml');
        $resource = $raml->getResourceByPath('/emails');
        $method = $resource->getMethod('get');
        $response = $method->getResponse(200);
        $body = $response->getBodyByType('application/json');
        $type = $body->getType();

        $type->validate(json_decode('[{"subject":"totao","body":"tata"},{"subject":"toto","body":"tata"}]', true));
    }
}
