<?php

namespace TheRealGambo\Ramlfications\Test;

use TheRealGambo\Ramlfications\Parameters\UriParameter;

class UriParameterTest extends \PHPUnit_Framework_TestCase
{

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

//    public function testUriParameter()
//    {
//        $uri = new UriParameter([], 'example');
//        $this->assertTrue($uri->getRequired());
//
//        $uri->setRequired(false);
//        $this->assertFalse($uri->getRequired());
//    }
}