#%RAML 1.0 SecurityScheme
description: JWT Authentication using either Authorization header or access_token query parameter
type: x-custom
displayName: JWT Authentication
describedBy:
  headers:
    Authorization:
      description: Used to send a valid JWT access token.
      type: string
      pattern: ^Bearer\s[a-zA-Z0-9\-_]+?\.[a-zA-Z0-9\-_]+?\.(?:[a-zA-Z0-9\-_]+)?$
      example: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.XbPfbIHMI6arZ3Y922BhjWgQzWXcXNrz0ogtVhfEd2o
  queryParameters:
    access_token:
      description: Used to send a valid JWT access token.
      type: string
      pattern: ^[a-zA-Z0-9\-_]+?\.[a-zA-Z0-9\-_]+?\.(?:[a-zA-Z0-9\-_]+)?$
      example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.XbPfbIHMI6arZ3Y922BhjWgQzWXcXNrz0ogtVhfEd2o
  responses:
    401:
      description: The request could not be processed because your authentication credentials are invalid.
    403:
      description: The request could not be processed because you do not have access to this protected resource.
