#%RAML 1.0 SecurityScheme
type: Basic Authentication
displayName: Basic Authentication
description: Basic Authentication via HTTP Authentication header
describedBy:
  headers:
    Authorization:
      type: string
      required: true
