#%RAML 1.0
title: headers

/:
  get:
    headers:
      example1:
        type: string
        description: simple description
        displayName: Example 1
        minLength: 4
        maxLength: 10
        required: true
        default: toto

      example2:
        type: string
        description: enum options description
        displayName: Example 2
        enum: [ cat, dog, cow ]
        default: cow
        required: false

      example3:
        type: number
        description: numbers description
        displayName: Example 3
        required: true
        minimum: 20
        maximum: 50