#%RAML 1.0 DataType
type: array
displayName: ListApiResources
description: List all available API resources
example: |
  [
    "http://api.example.com/v1",
    "http://api.example.com/v1/books",
    "http://api.example.com/v1/books/{book_id}",
    "http://api.example.com/v1/authors",
    "http://api.example.com/v1/authors/{author_id}"
  ]
